sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t zixuanzhong/docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true zixuanzhong/docker-ci npm run test